### ISSUE TITLE
Logo Proposal for HaiCap

### ISSUE THREAD

**Issue by area55git** [ASHWINI-GUPTA/HaiCab#1]
Hi @ASHWINI-GUPTA , according to your logo design request sent by mail, this is my proposal for your logo.

[![LOGO_PROPOSAL_FOR_HAICAP.jpg](https://s33.postimg.cc/bovah4jv3/LOGO_PROPOSAL_FOR_HAICAP.jpg)](https://postimg.cc/image/t25kvzf63/)

[![LOGO_PROPOSAL_FOR_HAICAP_3.jpg](https://s33.postimg.cc/rpsh7lu73/LOGO_PROPOSAL_FOR_HAICAP_3.jpg)](https://postimg.cc/image/5qm2kedcr/)

[![LOGO_PROPOSAL_FOR_HAICAP_2.jpg](https://s33.postimg.cc/623ixem5r/LOGO_PROPOSAL_FOR_HAICAP_2.jpg)](https://postimg.cc/image/623ixem5n/)

**Comment by area55git** [comment]
These are just sketches, remember that you can suggest any change, and if you do not like any, we can make another one.

**Comment by area55git** [comment]
Personally I really like option 2

**Comment by area55git** [comment]
Perfect, I will correct the error. Did you like any of the proposals?

**Comment by area55git** [comment]
Do you need another new proposal?

**Comment by ASHWINI-GUPTA** [comment]
Option 2 is good.

**Comment by area55git** [comment]
I will send you several color options

[![LOGO_PROPOSAL_FOR_HICAR.jpg](https://s33.postimg.cc/6nsjgtgsf/LOGO_PROPOSAL_FOR_HICAR.jpg)](https://postimg.cc/image/4j86fqf5n/)

Which do you like?
